### ISSUE TITLE
[Bug] Invalid rule "@typescript-eslint/require-array-sort-compare"

### ISSUE THREAD

**Issue by walidkorchi** [theoludwig/eslint-config-conventions#1]
I currently have my own [standalone eslint-config](url), which is a life-saver for reducing number of devDependencies, by which I'm extending the `conventions` into the `.eslintrc` config file.
And so, every time I'm running eslint check types, I get the following error:

![image](https://user-images.githubusercontent.com/87608619/219635296-49835160-66e8-4ede-ada4-cc45d9cea8c3.png)

## Steps To Reproduce

1. git clone `https://github.com/Walidoux/react-ios15-icons` as an exemple **after updating all the dependencies** and **initializing my `@walidoux/eslint-config`**.
2. yarn && yarn lint:typescript

## The current behavior

Returns the error above. CI fails when trying to merge `feat/100+icons` with `develop` branch.
Source: *`https://github.com/Walidoux/react-ios15-icons/actions/runs/4203358456/jobs/7292648838`*

## The expected behavior

Should either output eslint errors as *exit 1* or exit 0 as the code respects all conventions.

**Comment by theoludwig** [comment]
Thanks for your report!

Closing this issue as it seems like it's not an issue with this npm package.
Please reopen if you think this is a mistake.
